# Form implementation generated from reading ui file '/home/nvz/pyphotos/photo-video-manager/src/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.locationBarLayout = QtWidgets.QHBoxLayout()
        self.locationBarLayout.setObjectName("locationBarLayout")
        self.comboBoxLocation = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxLocation.setEditable(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLocation.sizePolicy().hasHeightForWidth())
        self.comboBoxLocation.setSizePolicy(sizePolicy)
        self.comboBoxLocation.setObjectName("comboBoxLocation")
        self.locationBarLayout.addWidget(self.comboBoxLocation)
        self.mainVerticalLayout.addLayout(self.locationBarLayout)
        self.listWidgetDirs = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetDirs.sizePolicy().hasHeightForWidth())
        self.listWidgetDirs.setSizePolicy(sizePolicy)
        self.listWidgetDirs.setMinimumHeight(100)
        self.listWidgetDirs.setMaximumHeight(150)
        self.listWidgetDirs.setObjectName("listWidgetDirs")
        self.mainVerticalLayout.addWidget(self.listWidgetDirs)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutThumbnails = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayoutThumbnails.setObjectName("gridLayoutThumbnails")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainVerticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionEdit = QtGui.QAction(parent=MainWindow)
        self.actionEdit.setObjectName("actionEdit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass
